### ISSUE TITLE
Question about possible Geometries

### ISSUE THREAD

**Issue by fridolin11** [joaoadelazzari/FStr#6]
Dear Mr De Lazzari

Another question came up while using your tool, hopefully you don't mind if I ask it on here.

I analyzed different closed, cylindrical profiles and would like to improve the minimal loadfactor. One way to do so, is using longitudinal stringers to improve the wall stiffness at the section that is prone to local buckling. My question is, is the tool suited to analyze such a structure like in the picture below?

![image](https://user-images.githubusercontent.com/120100620/236197157-64da8c73-3872-401f-ad66-c8b662e7f920.png)

Or do you advise against using such a structure in your tool?

Kind regards,
Fridolin

**Comment by joaoadelazzari** [comment]
Dear Fridolin,

Thank you for your message. Please do not hesitate to ask any questions you may have.

I would like to inform you that our software is capable of analyzing prismatic shapes, provided that the correct coordinates and element incidences are entered into the system. Based on the profile you have provided, it seems to be suitable for analysis. However, I would like to emphasize the importance of inserting at least one node in each plane face in your model to increase the precision of the load factor. This is crucial because plane faces in your model can develop local buckling mode in very small longitudinal lengths, which may not be the mode you are looking for.

In such cases, I always recommend comparing your solution with other tools in the literature, such as CUFSM or GBTul, to ensure accuracy and reliability.

Please do not hesitate to contact me if you have any further questions or concerns.

Best regards,

Joao Alfredo de Lazzari

**Comment by fridolin11** [comment]
Dear Mr. de Lazzari

Thank you for your reply and for your inputs! I added the middle nodes and compared the results with the identical model in CUFSM and both programs deliver similar results so all good!

Result from CUFSM:
![image](https://github.com/joaoadelazzari/FStr/assets/120100620/75f9d8be-b753-4728-8f0d-f4c9d9b66393)

Result from FStr:
![image](https://github.com/joaoadelazzari/FStr/assets/120100620/72770b23-25d3-41b4-a38f-e13f5ecac77c)

Kind regards,

Fridolin
